### ISSUE TITLE
CAP on ChromeOS Dev (and Beta) channel crashing.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/player-chromeapp#37] opened 2015-03-30 20:43 UTC
Steps to reproduce:
1. Set up ChromeOS dev channel.
2. Set Rise CAP as kiosk app.
3. Reboot Chromebox.

Result:
Rise Player crashes repeatedly.

How it should work:
Rise Player should load as normal.

OS:
ChromeOS

Chrome Ver:
43.0.2334.4(dev)

**Comment by mfarooq2000** [comment] 2015-03-30 20:58
@btfrise I will check it out today.

**Comment by mfarooq2000** [comment] 2015-03-31 03:19
@btfrise My Samsung ChromeOS is finding 42.0.2305.2 as latest  version, I will check again tomorrow if 43.0.2334.4 is available for download.

Version 42.0.2305.2 dev (64-bit)
Platform 6797.0.0 (Official Build) dev-channel stumpy
Firmware Google_Stumpy.2.102.0

And the ASUS box is registered to RiseVision domain and is on stable version, I am unable to change the channel.

**Comment by mfarooq2000** [comment] 2015-03-31 14:32
@btfrise Now my ChromeOS is updated to 43.0.2334.4 and CAP is crashishing rightaway without giving chance to review logs, I will try to find other ways to find the cause.

**Comment by mfarooq2000** [comment] 2015-03-31 21:22
@btfrise I am unable to find reason, CAP is crashing right after setting Webview source property. And its failing most of the times but not always.
Its happening even in non-kiosk mode.

We may want to open issue with Google.

**Comment by btfrise** [comment] 2015-04-01 13:26
@mfarooq2000 please open the issue.

**Comment by mfarooq2000** [comment] 2015-04-01 13:57
@btfrise dev channel ON on Windows has been updated to 43.0.2342.2 which is even newer version than the one on ChromeOS. I will try recreate issue on Windows in a bit and will open Google issue accordingly.

**Comment by mfarooq2000** [comment] 2015-04-01 15:19
@btfrise issue opened https://code.google.com/p/chromium/issues/detail?id=472633

**Comment by btfrise** [comment] 2015-04-24 15:39
@mfarooq2000 Any updates on this?

**Comment by mfarooq2000** [comment] 2015-04-24 16:10
@btfrise lats comment on opened case is : #13 rockot@chromium.org
I have a reduced repro case; the crash seems limited to the (deprecated) chrome.socket API Still no obvious cause for the crash, and relevant code hasn't changed in a long time. In any case, repro attached. Launching the test app again while it's already running will consistently crash all instances of the app.

I have added a message asking if they think this issue will be fixed?
otherwise we will need to update CAP to remove deprecated chrome.socket api and start using new chrome.socket.tcp api.

**Comment by btfrise** [comment] 2015-04-24 16:11
@mfarooq2000 Thanks, let @alanclayton and I know how you will proceed.

**Comment by btfrise** [comment] 2015-04-24 16:20
FYI @mfarooq2000 @alanclayton This is now happening on beta channel.

**Comment by alanclayton** [comment] 2015-04-24 16:26
@mfarooq2000 If chrome.sockeet is deprecated we should move to use the chrome.socket.tcp api. Can you confirm what this change impacts on the Player? In terms of priority, can you start this after the news hrd migration.

**Closed** 2016-02-03 14:34 UTC
Labels: bug
